version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
   # commands:
    #   - 
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       - touch /tmp/test && touch /tmp/test22
       - ls -la && pwd && ls -la /home/ && find / -name github.sh
  post_build:
    commands:
       - echo $CODEBUILD_BUILD_SUCCEEDING
       - PL_NUMBER=`echo $CODEBUILD_SOURCE_VERSION | cut -c 4-`
       - echo $PL_NUMBER
       - echo 'bash github.sh $TOKEN $CODEBUILD_BUILD_SUCCEEDING $PL_NUMBER'
artifacts:
  files:
     - /tmp/*
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
